# 인공지능프로그래밍

In [ ]:
import numpy as np
test_array=np.array([1,4,5,8],float)

In [ ]:
print(test_array)

[1. 4. 5. 8.]


In [ ]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [ ]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [ ]:
a = np.array([10,20,30])
a*10

array([100, 200, 300])

In [ ]:
import numpy as np

np.random.seed(85)
a = np.arange(1, 46)
np.random.shuffle(a)
lotto = a[:6]

print('lotto = ', lotto)

lotto =  [22  9 15 44 39 37]


In [ ]:
import numpy as np

np.random.seed(85)
a = np.arange(1, 46)
np.random.shuffle(a)
lotto = a[:6]

print('lotto = ', lotto)

lotto =  [22  9 15 44 39 37]


In [ ]:
import numpy as np

np.random.seed(85)
results = []

for _ in range(3):
    a = np.arange(1, 46)
    np.random.shuffle(a)
    lotto = a[:6]
    results.append(lotto)

lotto_array = np.array(results)

print('lotto_array = \n', lotto_array)

lotto_array = 
 [[22  9 15 44 39 37]
 [ 7 31 24 40 11 16]
 [ 8  3 23 40 38 32]]


In [ ]:
import numpy as np


for _ in range(3):
    a = np.arange(1, 46)
    np.random.shuffle(a)
    lotto = a[:6]
    results.append(lotto)

lotto_array = np.array(results)

print('lotto_array = \n', lotto_array)

lotto_array = 
 [[22  9 15 44 39 37]
 [ 7 31 24 40 11 16]
 [ 8  3 23 40 38 32]
 [28  8 43 23 22 35]
 [16 11 30 18 10 12]
 [24 32 17 16 43 33]]


In [ ]:
import numpy as np

shape = (3,4,5)
arr = np.random.randint(0,10,shape)

print(arr)

[[[6 8 8 9 1]
  [0 7 0 8 3]
  [8 1 0 7 1]
  [6 6 0 4 6]]

 [[1 1 2 9 1]
  [9 6 2 0 0]
  [0 0 3 5 8]
  [5 2 1 6 6]]

 [[6 5 8 1 6]
  [7 8 8 1 4]
  [8 0 4 2 7]
  [6 1 7 6 9]]]


In [ ]:
import numpy as np

shape = (3,3,6)  #3차원배열
arr = np.random.randint(0,20,shape)

print(arr)

[[[ 3  7 15  0  0 19]
  [ 0 17  7 12  1 12]
  [ 7  1 19 11 13  6]]

 [[ 5 18  2  1 14  3]
  [ 0 10  4  5  6 15]
  [19  2 17  1 14  4]]

 [[ 2 12  9  5 19  5]
  [ 7  2 19  1  5  3]
  [ 1  7  5 10 14 12]]]


In [ ]:
import numpy as np

shape = (5,6)  #2차원배열
arr = np.random.randint(0,100,shape)

print(arr)

[[29 55 40 34 62  5]
 [10  7 69 90 51 98]
 [24 41 16 40 33 87]
 [83 21  8 38 56  7]
 [ 3 97 96 96 33 43]]


In [ ]:
import numpy as np

temp = np.arange(48)

In [ ]:
print(temp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]


In [ ]:
import numpy as np

temp = np.arange(48)

array_3d = temp.reshape(4,3,4)  #3차원배열
print(array_3d)

array_2d = temp.reshape(6,8)   #2차원배열
print(array_2d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]
